# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca71a5fbeb52d24dec9b9f1f4f05f16491f9fed310b8f1198fc56a8c0fe5c9f902c823475892db9e84d6cd503a8b0065682d89532c58e2bc8abcd30235be7d90

test:
  secret_key_base: 063629ff271715d4c8e6633d584bd7ba77cf653f494bac4465121a0a47efd6e27afa9f846e1605e933907e88347094979ea582f179e25f46c02df55696995af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
